/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#9fe870",
        "on-primary": "#0e0f0c",
        "primary-active": "#cdffad",
        "primary-neutral": "#c5edab",
        "primary-pale": "#162310",
        ink: "#e8ebe6",
        "ink-deep": "#9fe870",
        body: "#888b86",
        mute: "#525550",
        canvas: "#161915",
        "canvas-soft": "#0c0f0b",
        surface: "#1e211d",
        positive: "#4ade80",
        "positive-deep": "#86efac",
        warning: "#ffd11a",
        "warning-deep": "#f59e0b",
        "warning-content": "#fde68a",
        negative: "#f87171",
        "negative-deep": "#fca5a5",
        "negative-darkest": "#fca5a5",
        "negative-bg": "#450a0a",
        "accent-orange": "#ffc091",
        "accent-cyan": "#38c8ff",
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        pill: "9999px",
      },
      fontFamily: {
        sans: ["DMSans_400Regular", "System"],
        "sans-medium": ["DMSans_500Medium", "System"],
        "sans-semibold": ["DMSans_600SemiBold", "System"],
        "sans-bold": ["DMSans_700Bold", "System"],
        "sans-black": ["DMSans_700Bold", "System"],
      },
      spacing: {
        xxs: "2px",
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        "2xl": "32px",
        "3xl": "48px",
      },
    },
  },
  plugins: [],
};
