"""add is_verified to users

Revision ID: 327f89d52e33
Revises: 5189074421f2
Create Date: 2026-05-11 21:37:16.288467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '327f89d52e33'
down_revision: Union[str, None] = '5189074421f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
