"""initial_schema

Revision ID: fc577e694ccf
Revises: 
Create Date: 2026-05-13 17:41:59.731099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc577e694ccf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('monthly_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('quest_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_monthly_quests_year_month')
    )
    op.create_index(op.f('ix_monthly_quests_id'), 'monthly_quests', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('home_ownership', sa.String(length=20), nullable=True),
    sa.Column('cb_person_cred_hist_length', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('rank', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nik'), 'users', ['nik'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_holder_name', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_table('credit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_on_file', sa.String(length=1), nullable=False),
    sa.Column('cred_hist_length', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_history_id'), 'credit_history', ['id'], unique=False)
    op.create_index(op.f('ix_credit_history_user_id'), 'credit_history', ['user_id'], unique=True)
    op.create_table('kyc_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ktp_image_url', sa.Text(), nullable=True),
    sa.Column('kk_image_url', sa.Text(), nullable=True),
    sa.Column('selfie_image_url', sa.Text(), nullable=True),
    sa.Column('bank_letter_url', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_documents_id'), 'kyc_documents', ['id'], unique=False)
    op.create_index(op.f('ix_kyc_documents_user_id'), 'kyc_documents', ['user_id'], unique=True)
    op.create_table('loan_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loan_amnt', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('loan_intent', sa.String(length=30), nullable=False),
    sa.Column('loan_grade', sa.String(length=2), nullable=False),
    sa.Column('loan_int_rate', sa.Float(), nullable=False),
    sa.Column('loan_percent_income', sa.Float(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('monthly_installment', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ml_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('loan_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_created_at'), 'loan_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_loan_applications_id'), 'loan_applications', ['id'], unique=False)
    op.create_index(op.f('ix_loan_applications_loan_status'), 'loan_applications', ['loan_status'], unique=False)
    op.create_index(op.f('ix_loan_applications_user_id'), 'loan_applications', ['user_id'], unique=False)
    op.create_table('otp_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_tokens_id'), 'otp_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_otp_tokens_user_id'), 'otp_tokens', ['user_id'], unique=False)
    op.create_table('user_employment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('emp_length', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('annual_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_employment_id'), 'user_employment', ['id'], unique=False)
    op.create_index(op.f('ix_user_employment_user_id'), 'user_employment', ['user_id'], unique=True)
    op.create_table('user_quest_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', 'quest_id', name='uq_user_quest_progress')
    )
    op.create_index(op.f('ix_user_quest_progress_id'), 'user_quest_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_quest_progress_user_id'), 'user_quest_progress', ['user_id'], unique=False)
    op.create_table('xp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('xp_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_events_created_at'), 'xp_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_xp_events_id'), 'xp_events', ['id'], unique=False)
    op.create_index(op.f('ix_xp_events_user_id'), 'xp_events', ['user_id'], unique=False)
    op.create_table('repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('penalty', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('midtrans_order_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('midtrans_order_id')
    )
    op.create_index(op.f('ix_repayments_due_date'), 'repayments', ['due_date'], unique=False)
    op.create_index(op.f('ix_repayments_id'), 'repayments', ['id'], unique=False)
    op.create_index(op.f('ix_repayments_loan_id'), 'repayments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_repayments_status'), 'repayments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repayments_status'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_loan_id'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_id'), table_name='repayments')
    op.drop_index(op.f('ix_repayments_due_date'), table_name='repayments')
    op.drop_table('repayments')
    op.drop_index(op.f('ix_xp_events_user_id'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_id'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_created_at'), table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_index(op.f('ix_user_quest_progress_user_id'), table_name='user_quest_progress')
    op.drop_index(op.f('ix_user_quest_progress_id'), table_name='user_quest_progress')
    op.drop_table('user_quest_progress')
    op.drop_index(op.f('ix_user_employment_user_id'), table_name='user_employment')
    op.drop_index(op.f('ix_user_employment_id'), table_name='user_employment')
    op.drop_table('user_employment')
    op.drop_index(op.f('ix_otp_tokens_user_id'), table_name='otp_tokens')
    op.drop_index(op.f('ix_otp_tokens_id'), table_name='otp_tokens')
    op.drop_table('otp_tokens')
    op.drop_index(op.f('ix_loan_applications_user_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_loan_status'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_created_at'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index(op.f('ix_kyc_documents_user_id'), table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_id'), table_name='kyc_documents')
    op.drop_table('kyc_documents')
    op.drop_index(op.f('ix_credit_history_user_id'), table_name='credit_history')
    op.drop_index(op.f('ix_credit_history_id'), table_name='credit_history')
    op.drop_table('credit_history')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_nik'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_monthly_quests_id'), table_name='monthly_quests')
    op.drop_table('monthly_quests')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
